packages:
  - playground

enableGlobalVirtualStore: true

enablePrePostScripts: false

ignorePatchFailures: false

onlyBuiltDependencies:
  - core-js
  - dprint

optimisticRepeatInstall: true

resolutionMode: lowest-direct

strictDepBuilds: true
